server:
  port: 5503
  host: localhost
auth:
  jwksUri: http://localhost:5501/.well-known/jwks.json
database:
  url: mongodb+srv://pranjalarora98:jVxrgy3liVbP0g1c@cluster0.efn7t.mongodb.net/
stripe:
  security: sk_test_51PtnnISD01onqdsKtrcw6t51xpVTAIZoa948hUsEez0iyHJ8sqQv92QKTrtV6A6izcZx536vBPwph8dtxhkh2r0w00XQpTCUUJ